### PR TITLE
replaced dart:html with package:web

### PR DESCRIPTION
**Pull request by huanghui1998hhh**
By the way, maybe publishing a transitional version GetX to let web use WASM is better!

### CODE REVIEW

**Comment by ot-repo** [comment]
Hello, when are you planning to approve this PR? I want to use wasm and get_storage is now a blocker for us. I would really appreciate it, if you can approve it as soon as possible.

Thank you!

**Comment by ot-repo** [comment]
Hi @huanghui1998hhh may I ask you, why you have closed the PR?

**Comment by huanghui1998hhh** [comment]
> Hi @huanghui1998hhh may I ask you, why you have closed the PR?

I found that some changes were committed to the wrong branch (my bad), so I have to close the PR.
Don't worry, I'll open a new one later.

By the way, if you want to build web with `wasm`, only update the `package:web` in `get_storage` is not enough. 
`get_storage` dependence on `get`, but `get` still dependence `dart:html`. So we can't build `wasm` until @jonataslaw publish a new version `get`.
In my case, i remove the whole `get_connect` module to remove `dart:html`. This is a simple way for me. 
So, in my suggestion, if you just using `get_storage`, you can use something like `shared_preferences` instead it.

**Comment by ot-repo** [comment]
Oh I see, thank you for the explanation. For the time being I forked get_storage to solve this issue temporarily bis @jonataslaw updates the dependencies and merge you PR.

**Comment by TheLastFlame** [comment]
> So, in my suggestion, if you just using `get_storage`, you can use something like `shared_preferences` instead it.

Unfortunately for me personally this option is impossible.  My application already uses get_storage and stores data of tens of thousands of users. There is no adequate way to migrate this data from get_storage somewhere else.

**Comment by mbfakourii** [comment]
cc @jonataslaw

**Pull request closed without merging**
